name: Excel Comparator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    uses: denqiu/reusable-tools/.github/workflows/python/py-setup-test.yml@main
    with:
      version: 3.12
      install_file: requirements.txt
      test_folder: tests